# Generated by Django 4.1 on 2022-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=500)),
                ('qtd_max_marmitas', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link', models.CharField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-qtd_max_marmitas'],
            },
        ),
    ]
