# Generated by Django 4.1 on 2022-09-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kit',
            table='kits',
        ),
    ]
