# Generated by Django 4.1 on 2022-09-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_kit_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marmita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True)),
                ('descricao', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'ordering': ['qtd_max_marmitas']},
        ),
    ]
