# Generated by Django 4.1 on 2022-09-07 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_marmita_alter_kit_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itemPedido', to='produtos.kit')),
                ('marmitas', models.ManyToManyField(to='produtos.marmita')),
            ],
            options={
                'ordering': ['kit'],
            },
        ),
    ]
